name: Release GitHub Actions

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release"
        required: true
      script:
        description: "Specify script to execute"
        required: false
        default: "yarn build"

permissions:
  contents: read

jobs:
  release:
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: step-security/reusable-workflows/.github/workflows/actions_release.yaml@v1
    with:
      tag: "${{ github.event.inputs.tag }}"
      script: ${{ github.event.inputs.script || 'yarn build' }}