name: Yarn Audit Fix Run

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Specify a base branch"
        required: false
        default: "main"
      package_manager:
        description: "Specify package manager (npm or yarn)"
        required: false
        default: "yarn"
      script:
        description: "Specify script to execute"
        required: false
        default: "yarn build"
      yarn_version:
        required: false
        type: string
        default: "3.6.3"

  schedule:
    - cron: "0 0 * * 1"

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      base_branch: ${{ github.event.inputs.base_branch || 'main' }}
      package_manager: "yarn"
      script: ${{ github.event.inputs.script || 'yarn build' }}
      yarn_version: '3.6.3'

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write