name: Auto Cherry-Pick from Upstream

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to create the PR against"
        required: true
        default: "main"
      script:
        description: "Specify the npm/yarn script to run if available"
        required: false
        default: "yarn run all"
      package_manager:
        description: "Specify package manager if available (npm or yarn)"
        required: false
        default: "yarn"
      yarn_version:
        required: false
        type: string
        default: "3.6.3"
      mode:
        description: "Run mode: cherry-pick or verify"
        required: false
        default: "cherry-pick"
      node_version:
        description: "Specify Node.js version (e.g., '18', '20', 'lts/*')"
        required: false
        default: "24"

  pull_request:
    types: [labeled, opened, synchronize]      

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write

jobs:
  cherry-pick:
    if: github.event_name == 'workflow_dispatch' || contains(fromJson(toJson(github.event.pull_request.labels)).*.name, 'review-required')
    uses: step-security/reusable-workflows/.github/workflows/auto_cherry_pick.yaml@v1
    with:
      original-owner: "crazy-max"
      repo-name: "ghaction-import-gpg"
      base_branch: ${{ inputs.base_branch }}
      script: ${{ inputs.script }}
      package_manager: ${{ inputs.package_manager }}
      yarn_version: '3.6.3'
      mode: ${{ github.event_name == 'pull_request' && 'verify' || inputs.mode }}
      node_version: "${{ inputs.node_version || '24' }}"
